### ISSUE TITLE
Add Fakegato

### ISSUE THREAD

**Issue by electromitter** [SteidlD/homebridge-inkbird-bt-thsensor#1]
Thanks for this Plugin.
Is ist possible to add Fakegato ?

**Comment by SteidlD** [comment]
You're welcome. Hope the installation was easy and went all well. Would be nice to have some feed-back.
Fakegato: I'm already working on it ;-)

**Comment by electromitter** [comment]
Everything went well. I have 2 Sensors for my Fish Tanks. 1 with Display and the other without display.  Both work well with this Plugin.

**Comment by SteidlD** [comment]
Perfect. If you write me the models (i.e. IBS-TH1) I can add them to the list of supported devices. Did you set "model": "IBS-TH1" for both sensors so the checks are active?
In the next version I will add a log output for new sensor types, so I get the data and can add it to the checking routine..

**Comment by SteidlD** [comment]
Eve history included for temperature and humidity in version 0.3.0.
Have fun with it...
