### ISSUE TITLE
Support for M1 Gateway

### ISSUE THREAD

**Issue by myparanoidandroidlung** [SteidlD/homebridge-inkbird-bt-thsensor#12]
Hi! Does this plugin have support for the Inkbird M1 Gateway?
I am using a raspeberry pi with no bluetooth.

Thanks!

**Comment by SteidlD** [comment]
Hi @myparanoidandroidlung ,

no sorry. This plugin only works with bluetooth.

**Comment by SteidlD** [comment]
Hi @myparanoidandroidlung,

I don't know if that works (I don't have a gateway), but look here:
[homebridge-inkbird-wifi-gateway](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway)

Somebody seems to be working on it....
