### ISSUE TITLE
Support for Fahrenheit Units

### ISSUE THREAD

**Issue by ccruiser** [SteidlD/homebridge-inkbird-bt-thsensor#14]
Currently I was able to discover my InkBird WiFi gateway (IBS-M1) via Bluetooth :) That said, it appears there is not an option for Fahrenheit units. Let me know if you need any additional info.

-CC

**Comment by SteidlD** [comment]
Hi @ccruiser,

sorry I cannot follow your idea. The Inkbird WiFi gateway in my understanding mirrows the bluetooth sensors in its area into the WiFi to be able to read out the values even when your outside bluetooth range...
But this plugin only communicates via bluetooth, not via WiFi/LAN frames. So the sensor always has to be within bluetooth range of the homebridge. An Inkbird WiFi plugin would be a completely new plugin with probably 95% different code... Sorry, not planing to develop this.
