### ISSUE TITLE
Is the hub needed or just the BT probe?

### ISSUE THREAD

**Issue by ShaunRoberts543** [SteidlD/homebridge-inkbird-bt-thsensor#18]
Hello, just wanted some clarification before I flip the switch on buying one of these for my pool.  Is the communication hub needed?  If not is there anything special I need to get the bluetooth to communicate with my smart home?  Sorry, everything I have now is Zigbee or WiFi and I am not familiar if I need some type of bluetooth dongle to pull data from sensor into plug-in.

Thanks,
Shaun

**Comment by sythesigh** [comment]
mine talks to my raspberry pi over bluetooth, through homebridge. No additional hardware needed
