### ISSUE TITLE
Using plugin with InkBird IBS-P01B through the IBS-M1S Hub

### ISSUE THREAD

**Issue by Hedrakk** [SteidlD/homebridge-inkbird-bt-thsensor#20]
Hi,
I’m really a newbie in this but your plugin seems to be the closest thing that could potentially work for my case. 

I was able to connect my Pool Thermometer (InkBird IBS-P01B) directly with your plugin, however, since this device is using BLE and that my HOOBS box is to far away from my swimming pool (for obvious reasons) the status of the device is constantly not responding. Even in the InkBird app, the device status is hit and miss. 

So I bought the InkBird Hub (IBS-M1S) and with it, the connection status is now steady. Now the problem is that I can’t find a way to connect that hub to my HOOBS box. The only InkBird plugin available on HOOBS seems to be yours. That’s why I’m asking you for help. 

I can provide you all the information you want, but as a noob, you will have to tell me how to give it to you :) 

Thanks in advance for your help.

**Comment by SteidlD** [comment]
Hi @Hedrakk,

see also issue #12... Sorry, but that cannot possibly work:
- The IBS-M1S gateway is translating BLE to WiFi network, but this plugin is trying to communicate over BLE only
- This would be a differnt plugin or a huge effort to programm this.
- I don't have this gateway and also I don't need it -> To be honest I don't have plans to work on this soon
