### ISSUE TITLE
Warning - Waiting for bluetooth low energy hardware to power on

### ISSUE THREAD

**Issue by JustTheD-lab** [SteidlD/homebridge-inkbird-bt-thsensor#3]
Hey, i wanted to use your plugin for my IBS-TH1 Plus with Hoobs. 
but all i get is this error message "Warning - Waiting for bluetooth low energy hardware to power on"

My System is freshly set up and no other plugin is installed

if i am looking for BT devices over Terminal i can see and find them so BT is working fine

**Comment by SteidlD** [comment]
Hey,
could you please send a log from the startup and some more information about your set up:
- version of plugin, homebridge, node
- did you run the setcap command without error described in the manual 1c?
- your accessory configuration

If you get the warning only once when starting up, that's ok. If you get it cyclic, the noble package cannot initialize your raspis BT hardware - then it could be the setcap.

**Comment by JustTheD-lab** [comment]
Hi there , 
The Plugin Version is 0.3.1 
Node Version  12.16.3
Homebridge Version is 1.1.2

when i run the set cap Command i get an error 

 ```
Failed to set capabilities on file `/home/hoobs/which' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```

I hope you have a tipp for me id think its only because i am new to the homebridge stuff

**Comment by SteidlD** [comment]
Hi,

did you solve the problem? I think it's not a problem of the plugin, but some linux rights problem - but I'm no expert on this. The running of the set cap command is a requirement for the use of the noble package, and is described there.

**Comment by SteidlD** [comment]
Hi @JustTheD-lab,

don't know if your still interested. I found out about your problem. I had a mistake in the manual for the setcap command (step 1.c). I wrote the command with ' instead of `. That's why it didn't work. Found it out recently when I set up a fresh raspi on my own and had the same problem.... I updated the manual. Now it should work.
