### ISSUE TITLE
Inkbird wifi temperature plug

### ISSUE THREAD

**Issue by justinpeterson13** [SteidlD/homebridge-inkbird-bt-thsensor#5]
Would this plugin work for a wifi inkbird product? Specifically:

Inkbird C929 WiFi Temperature Controller Digital Thermostat Heat Mat Greenhouse Thermostat https://www.amazon.ca/dp/B07K8L2FVB/ref=cm_sw_r_cp_api_i_JS5XQSRS7DEAYMF7PEN1

I’d like to integrate this into my homekit but I’m not sure how.

**Comment by SteidlD** [comment]
Hi Justin,
this cannot work at all, as this plugin only communicates via Bluetooth. It seems that your Wi-Fi temperature sensor even uses a different app on the mobile phone to communicate. So it only has the same company name but is a totally different product line... Sorry!
But you could try to record the communication between your app and the sensor. If it’s not ciphered it might be easy to write your own plugin. You could copy this plugin and just rewrite the communication and data extraction part ;-)
BR Dietmar
